version: "3"
services:
  front_end:
    image: httpd
    volumes:
      - ~/docker-1/html:/usr/local/apache2/htdocs
    ports:
      - 8080:80
    networks:
      - frontend
    depends_on:
      - back_end
  back_end:
    image: vhmds/simple-app
    ports:
      - "6000:5000"
    networks:
      - frontend
      - backend
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
networks:
  backe:
  frontend:
volumes:
  database:
  