- name : TASK
  hosts: all
  become: true

  tasks:
  - name: copy from remote to local
    fetch:
      src: /etc/os-release
      dest: /home/ahmed/depi
  
  - name: Read users from CSV file and return a dictionary
    read_csv:
      path: file/user.csv
    register: users
    delegate_to: localhost

  - name: display user_list data
    debug:
      var: users.list
  
  - name: create users
    user:
      name: "{{ item.Username }}"
      uid: "{{ item.UID }}"
      password: "{{ item.Password | password_hash('sha512') }}"
      state: present
    loop: "{{ users.list }}"
  - name: create the file
    copy:
      dest: /home/ahmed/depi
      content: "{{ ansible_distribution_version }}"